In [ ]:
from google.colab import files
uploaded = files.upload()

Saving tracks.csv to tracks.csv
Saving artist.csv to artist.csv
Saving albums.csv to albums (1).csv

In [ ]:
import pandas as pd

artist_df = pd.read_csv("artist.csv")
albums_df = pd.read_csv("albums (1).csv")
tracks_df = pd.read_csv("tracks.csv")

artist_df.head(), albums_df.head(), tracks_df.head()

(                       id                   name  artist_popularity  \
 0  6GkSLJj5CGLIckLIb8J4LR      Late Night Fights                  0
 1  1N0VwQy5PRJymrRvlRzDIj       Sub Par All Star                  0
 2  4Ch4BIKKwMJsiu1oVLDwpX  Nirvana Meditation 8D                  0
 3  5h2iINTOvhghVcpIzrztPP      Red Hot Rebellion                  0
 4  7dE2MLL2SaI6MujpU5HFVi   Nirvana Tribute Band                  0

           artist_genres  followers           genre_0 genre_1 genre_2 genre_3  \
 0  ['minneapolis punk']        184  minneapolis punk     NaN     NaN     NaN
 1     ['antiviral pop']        491     antiviral pop     NaN     NaN     NaN
 2                ['8d']         56                8d     NaN     NaN     NaN
 3       ['action rock']        394       action rock     NaN     NaN     NaN
 4           ['tribute']        230           tribute     NaN     NaN     NaN

   genre_4  genre_5  genre_6
 0     NaN      NaN      NaN
 1     NaN      NaN      NaN
 2     NaN      NaN      NaN
 3     NaN      NaN      NaN
 4     NaN      NaN      NaN  ,
             track_name                track_id  track_number  duration_ms  \
 0        Amazing Grace  6mN8nzCXWUeT5LWEcG1Utx             5       555521
 1         Silent Night  58sgjtx3FOnBBEOd3BQE6C             8       535041
 2      Ancient Canyons  45tQJhm0WSk5VWMZK3FsLK             1       545855
 3  Pacha Mama Medicina  3VFD7QqkJSg0OR6yBwKl7A             6       305241
 4      Palace Of Light  7LwJV5BEIC9BQnzvaBSyCc             7       351060

   album_type  artists  total_tracks             album_name  \
 0      album      NaN             9  Deep Peace Experience
 1      album      NaN             9  Deep Peace Experience
 2      album      NaN             9  Deep Peace Experience
 3      album      NaN             9  Deep Peace Experience
 4      album      NaN             9  Deep Peace Experience

               release_date               label  ...  artist_3 artist_4  \
 0  2015-06-09 00:00:00 UTC  Mountain Music Inc  ...       NaN      NaN
 1  2015-06-09 00:00:00 UTC  Mountain Music Inc  ...       NaN      NaN
 2  2015-06-09 00:00:00 UTC  Mountain Music Inc  ...       NaN      NaN
 3  2015-06-09 00:00:00 UTC  Mountain Music Inc  ...       NaN      NaN
 4  2015-06-09 00:00:00 UTC  Mountain Music Inc  ...       NaN      NaN

   artist_5 artist_6 artist_7 artist_8 artist_9 artist_10 artist_11  \
 0      NaN      NaN      NaN      NaN      NaN       NaN       NaN
 1      NaN      NaN      NaN      NaN      NaN       NaN       NaN
 2      NaN      NaN      NaN      NaN      NaN       NaN       NaN
 3      NaN      NaN      NaN      NaN      NaN       NaN       NaN
 4      NaN      NaN      NaN      NaN      NaN       NaN       NaN

   duration_sec
 0      555.521
 1      535.041
 2      545.855
 3      305.241
 4      351.060

 [5 rows x 26 columns],
                        id  track_popularity  explicit
 0  02MBhqgR7WeeI4ZfB6Lo0i                 0     False
 1  5j4M4gLYuUy9PVw0vsXWyq                 0     False
 2  46EucLPJpx0QM3SCjzzdP0                 0     False
 3  4nK2LvW3osgDT89S38Mcg6                 0     False
 4  1Pq37WIQZDG7yNFnY5IbqG                 0     False)

In [ ]:
artist_df.info()
albums_df.info()
tracks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37012 entries, 0 to 37011
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 37012 non-null  object
 1   name               37012 non-null  object
 2   artist_popularity  37012 non-null  int64
 3   artist_genres      37012 non-null  object
 4   followers          37012 non-null  int64
 5   genre_0            10947 non-null  object
 6   genre_1            4820 non-null   object
 7   genre_2            2440 non-null   object
 8   genre_3            1365 non-null   object
 9   genre_4            718 non-null    object
 10  genre_5            0 non-null      float64
 11  genre_6            0 non-null      float64
dtypes: float64(2), int64(2), object(8)
memory usage: 3.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438973 entries, 0 to 438972
Data columns (total 26 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_name        438968 non-null  object
 1   track_id          438973 non-null  object
 2   track_number      438973 non-null  int64
 3   duration_ms       438973 non-null  int64
 4   album_type        438973 non-null  object
 5   artists           0 non-null       float64
 6   total_tracks      438973 non-null  int64
 7   album_name        438972 non-null  object
 8   release_date      438950 non-null  object
 9   label             438921 non-null  object
 10  album_popularity  438973 non-null  int64
 11  album_id          438973 non-null  object
 12  artist_id         438973 non-null  object
 13  artist_0          438970 non-null  object
 14  artist_1          100485 non-null  object
 15  artist_2          43650 non-null   object
 16  artist_3          16362 non-null   object
 17  artist_4          7173 non-null    object
 18  artist_5          3945 non-null    object
 19  artist_6          2549 non-null    object
 20  artist_7          0 non-null       float64
 21  artist_8          0 non-null       float64
 22  artist_9          0 non-null       float64
 23  artist_10         0 non-null       float64
 24  artist_11         0 non-null       float64
 25  duration_sec      438973 non-null  float64
dtypes: float64(7), int64(4), object(15)
memory usage: 87.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438938 entries, 0 to 438937
Data columns (total 3 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                438938 non-null  object
 1   track_popularity  438938 non-null  int64
 2   explicit          438938 non-null  bool
dtypes: bool(1), int64(1), object(1)
memory usage: 7.1+ MB

In [ ]:
artist_df.drop_duplicates(inplace=True)
albums_df.drop_duplicates(inplace=True)
tracks_df.drop_duplicates(inplace=True)

In [ ]:
artist_df.isna().sum()
albums_df.isna().sum()
tracks_df.isna().sum()

id                  0
track_popularity    0
explicit            0
dtype: int64

In [ ]:
# Check referential integrity
albums_df['artist_id'].isin(artist_df['id']).value_counts()
albums_df['track_id'].isin(tracks_df['id']).value_counts()

track_id
True     438963
False        10
Name: count, dtype: int64

In [ ]:
artist_album_df = pd.merge(
    albums_df,
    artist_df,
    left_on="artist_id",
    right_on="id",
    how="left"
)

In [ ]:
fact_tracks_df = pd.merge(
    tracks_df,
    artist_album_df,
    left_on="id",
    right_on="track_id",
    how="left"
)

In [ ]:
fact_tracks = fact_tracks_df[[
    'track_id',
    'track_name',
    'album_id',
    'artist_id',
    'duration_ms',
    'track_popularity'
]]

In [ ]:
dim_artist = artist_df[['id', 'name', 'genre_0']]
dim_album = albums_df[['album_id', 'album_name', 'release_date']]

In [ ]:
fact_tracks.to_csv("fact_tracks.csv", index=False)
dim_artist.to_csv("dim_artist.csv", index=False)
dim_album.to_csv("dim_album.csv", index=False)

In [ ]:
files.download("fact_tracks.csv")
files.download("dim_artist.csv")
files.download("dim_album.csv")